version: '3.1'
services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/seed.sql:/docker-entrypoint-initdb.d/seed.sql 
    ports:
      - 5432:5432

  app:
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
        - .env
